.RECIPEPREFIX = >
.PHONY: generate_schema install_nodejs_sdk build_nodejs_sdk

generate_schema:
> @echo "Generating schema"

install_nodejs_sdk:
> @echo "Installing NodeJS SDK"

build_nodejs_sdk:
> npm pack
