name: Setup Go Environment
description: Sets up Go, caches build and module cache, and downloads dependencies
inputs:
  go-version:
    description: Go version to install
    required: true
  working-directory:
    description: Directory containing go.mod
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Cache Go build and mod cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ working-directory }}/go.mod
        cache: false

    - name: Download Go modules
      run: |
        cd ${{ inputs.working-directory }}
        go mod download
      shell: bash
