name: Setup Node Environment
description: Installs Node.js and primes dependency caches
inputs:
  node-version:
    description: Node.js version to install
    required: false
    default: '22'
  working-directory:
    description: Directory containing package manager lock file
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
        cache-dependency-path: ${{ inputs.working-directory }}/yarn.lock
