name: Local Pulumi CI Test (Golang)

on:
  push:

jobs:
  test-workflow:
    uses: ./.github/workflows/golang-test-lint.yaml
    with:
      setup-action: 'setup-pulumi-env'
      working-directory: 'testdata/golang'
