name: Golang Pulumi Test and Linting

on:
  workflow_call:
    inputs:
      test-flags:
        required: false
        type: string
        default: '-v'
      working-directory:
        required: false
        type: string
        default: '.'
      disable-linter:
        required: false
        type: boolean
        default: false


jobs:
  run-unit-test:
    name: Run unit tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Act dependencies
        if: ${{ env.ACT }}
        uses: ./.github/actions/setup-act-env

      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          repository: spigell/my-shared-workflows
          path: .github/actions-temp

      - name: Move actions into correct path
        run: |
          rsync -a .github/actions-temp/.github/actions/ .github/actions/

      - name: Setup Go and install deps
        uses: ./.github/actions/setup-pulumi-env
        with:
          runtime: go
          working-directory: ${{ inputs.working-directory }}

      - name: Run unit tests
        run: |
          cd ${{ inputs.working-directory }}
          set -o pipefail
          go test ${{ inputs.test-flags }} $(go list ./... | grep -v integration | grep -v crds/generated)

  run-linter:
    name: Run linter
    if: ${{ !inputs.disable-linter }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Act dependencies
        if: ${{ env.ACT }}
        uses: ./.github/actions/setup-act-env

      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          repository: spigell/my-shared-workflows
          path: .github/actions-temp

      - name: Move actions into correct path
        run: |
          rsync -a .github/actions-temp/.github/actions/ .github/actions/

      - name: Setup Go and install deps
        uses: ./.github/actions/setup-pulumi-env
        with:
          runtime: go
          working-directory: ${{ inputs.working-directory }}

      - name: Run the golangci linter
        uses: golangci/golangci-lint-action@v8
        with:
          skip-cache: true
          working-directory: ${{ inputs.working-directory }}
          args: --timeout=10m
          version: v2.1.6
