name: The prebuilt binaries release

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
      setup-action:
        required: false
        type: string
        default: 'setup-go-env'
      config-path:
        required: false
        type: string
        default: .goreleaser.yaml
    secrets:
      gh-token:
        required: true

jobs:
  goreleaser:
    name: "Run Goreleaser"
    runs-on: ubuntu-24.04
    steps:
      - name: Validate ref
        if: ${{ !env.ACT }}
        env:
          GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_EVENT_BASE_REF: ${{ github.event.base_ref }}
        run: |
          node -e '
            const ref = process.env.GITHUB_REF;
            console.log("Current ref:", ref);

            const baseRef = process.env.GITHUB_EVENT_BASE_REF;
            const defaultBranch = process.env.GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH;

            const isDefaultBranch = baseRef === `refs/heads/${defaultBranch}`;
            if (!isDefaultBranch) {
              console.log(`Not Valid: must be running on default branch (${defaultBranch})`);
              process.exit(1);
            }

            const isTag = ref.startsWith("refs/tags/");
            if (!isTag) {
              console.log(`Not Valid: must be running on tag (${ref})`);
              process.exit(1);
            }

            console.log("✅ Valid ref:", ref);
          '

      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Get actions
        if: ${{ !env.ACT }}
        run: |
          git clone "$GITHUB_SERVER_URL/spigell/my-shared-workflows" ./.github/actions_ext

      - name: Install Act dependencies
        if: ${{ env.ACT }}
        uses: ./.github/actions/setup-act-env

      # Ignore the external actions folder so the tree stays clean for GoReleaser
      - name: Ignore external actions folder
        run: |
          echo ".github/actions_ext" >> .git/info/exclude
          git status --porcelain

      - name: Setup Basic env
        if: ${{ inputs.setup-action == 'setup-go-env' }}
        uses: ./.github/actions_ext/.github/actions/setup-go-env
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Setup Pulumi Go env
        if: ${{ inputs.setup-action == 'setup-pulumi-env' }}
        uses: ./.github/actions_ext/.github/actions/setup-pulumi-env
        with:
          runtime: go
          working-directory: ${{ inputs.working-directory }}

      - name: Release required binaries
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          args: release --clean --verbose --config ${{ inputs.config-path }}
          version: '2.11.0'
          workdir: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}
