name: The NPM package uploading

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
      setup-action:
        required: false
        type: string
        default: 'setup-node-env'
      platform:
        required: false
        type: string
        default: 'npm'
      package-directory:
        required: false
        type: string
        default: '.'
      build-command:
        required: false
        type: string
        default: 'npm install'
      dry-run:
        required: false
        type: boolean
        default: false
    secrets:
      token:
        required: true

jobs:
  run-release:
    name: "Release NodeJS package"
    runs-on: ubuntu-24.04
    steps:
      - name: Validate ref
        if: ${{ !env.ACT }}
        env:
          GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_EVENT_BASE_REF: ${{ github.event.base_ref }}
        run: |
          node -e '
            const ref = process.env.GITHUB_REF;
            console.log("Current ref:", ref);

            const baseRef = process.env.GITHUB_EVENT_BASE_REF;
            const defaultBranch = process.env.GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH;

            const isDefaultBranch = baseRef === `refs/heads/${defaultBranch}`;
            if (!isDefaultBranch) {
              console.log(`Not Valid: must be running on default branch (${defaultBranch})`);
              process.exit(1);
            }

            const isTag = ref.startsWith("refs/tags/");
            if (!isTag) {
              console.log(`Not Valid: must be running on tag (${ref})`);
              process.exit(1);
            }

            console.log("✅ Valid ref:", ref);
          '

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get actions
        if: ${{ !env.ACT }}
        run: |
          git clone "$GITHUB_SERVER_URL/spigell/my-shared-workflows" ./.github/actions_ext

      - name: Install Act dependencies
        if: ${{ env.ACT }}
        uses: ./.github/actions/setup-act-env

      - name: Setup Node env
        if: ${{ inputs.setup-action == 'setup-node-env' }}
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Pulumi env
        if: ${{ inputs.setup-action == 'setup-pulumi-env' }}
        uses: ./.github/actions_ext/.github/actions/setup-pulumi-env
        with:
          runtime: nodejs
          working-directory: ${{ inputs.working-directory }}

      - name: Generate nodejs sdk package
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.build-command }}

      - name: Configure npmrc for Github registry
        if: ${{ inputs.platform == 'github' }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.token }}" > ${{ inputs.package-directory }}/.npmrc
          echo "@spigell:registry=https://npm.pkg.github.com" >> ${{ inputs.package-directory }}/.npmrc

      - name: Publish package to the registry
        uses: JS-DevTools/npm-publish@v3
        with:
          package: ${{ inputs.package-directory }}
          token: ${{ secrets.token }}
          dry-run: ${{ inputs.dry-run }}
