name: Verify Shared Workflows

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  golang-verify:
    uses: ./.github/workflows/golang-test-lint.yaml
    with:
      working-directory: 'testdata/golang'

  nodejs-verify:
    uses: ./.github/workflows/nodejs-test-lint.yaml
    with:
      working-directory: 'testdata/nodejs'
      node-version: '22'
      test-flags: 'run'
      eslint-flags: '.'

  python-verify:
    uses: ./.github/workflows/python-test-lint.yaml
    with:
      working-directory: 'testdata/python'
      python-version: '3.13.7'
      disable-linter: false
